### ISSUE TITLE
Не обновляется дбм

### ISSUE THREAD

**Issue by AhalayMaxalay** [Aleksart163/DBM-RV-DF#1]
https://www.youtube.com/watch?v=oYrRHnj0V00
полный перезаход, полное удаление не помогает

**Comment by Aleksart163** [comment]
Приветствую! Извиняюсь за долгий ответ, давно уже сюда не заходил на сайт ...)
Ты немного неправильно делаешь обновление - при таком переносе как у тебя надо полностью потом перезаходить в игру, команда /reload в таком случае не сработает. Она работает лишь когда ты в файле что-то меняешь, а когда сам файл полностью меняется на новый, то такое уже не сработает.

И между прочим, рекомендую использовать файл UpdateDBM, что находится в папке с аддонами. Он автоматически в 1 нажатие и примерно в 5 сек(по крайней мере так происходит у меня) обновляет твой аддон до последней актуальной версии. После этого так же необходимо полностью перезайти в игру, или делать это до входа.

Там скачивается сразу же архив с последней версией, вынимается все из папки и полностью все твои файлы аддона заменяются на новые, а дальше архив просто удаляется. Очень легко и быстро всё происходит) (работает на винде 10 и выше)

**Comment by AhalayMaxalay** [comment]
Спасибо) Раньше без проблем обновлял полностью аддон как показал на видео - проблем не было. Также и update использовал - не получилось обновить. К слову после того как я кинул сюда видео на некст день новой обновой аддона все пофиксилось, так что уже неактуально. За аддон спасибо отдельное

**Comment by Aleksart163** [comment]
та нз, спасибо за использование) не только же этим для себя занимаюсь, но и для других)
